### ISSUE TITLE
[BUG] error trying to connect: tls handshake eof

### ISSUE THREAD

**Issue by tomas-zijdemans-vipps** [slackapi/deno-slack-runtime#58]
I have a workflow that runs daily, haven't made changes to it for some time. Got this error today. Maybe a hiccup on the backend?

```
2023-11-13 08:00:50 [info] [Fn060X3USBNZ] (Trace=Tr0657KMM4GN) Function output:
        Caught error from user supplied module: TypeError: error sending request for url (https://slack.com/api/functions.completeSuccess): error trying to connect: tls handshake eof
            at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
            at async fetch (ext:deno_fetch/26_fetch.js:504:7)
            at async BaseSlackAPIClient.apiCall (file:///opt/runtime.js:44:22)
            at async Object.RunFunction [as function_executed] (file:///opt/runtime.js:1709:29)
            at async DispatchPayload (file:///opt/runtime.js:1790:16)
            at async run (file:///opt/runtime.js:1857:18)
            at async serveHttp (file:///opt/runtime.js:1885:38)
        Error responding HTTP 500 to webapp request: Http: connection closed before message completed
```

**Comment by filmaj** [comment]
Hey @tomas-zijdemans-vipps I transferred this issue from deno-slack-sdk to deno-slack-runtime, which houses the specific code your stack trace logged out.

Can you confirm what time zone your logs are based in? I don't see any obvious problems with the `functions.completeSuccess` API this week, but there may be further areas of failure on our hosting side that I can investigate.

**Comment by filmaj** [comment]
And one more question @tomas-zijdemans-vipps : how many times did you see this happen? If only a handful of times, perhaps we should consider some manner of fallback or retry behaviour if we can catch this specific error... what do you think @WilliamBergamin ?

**Comment by WilliamBergamin** [comment]
If this happens enough a retry behavior may be worth while 💯

**Comment by tomas-zijdemans-vipps** [comment]
I only caught the error once (it could have happened more times, but everything has run fine the past couple of days).
@filmaj : I am on Oslo time (GMT+1)
